name: build

on:
  release:
    types: [prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: aarch64-macos
            cpu: apple_m1
          - target: x86_64-linux
            cpu: haswell # amd64 compatibility build
          - target: x86_64-linux
            cpu: znver4  # amd64 zen4 build
          - target: aarch64-linux
            cpu: neoverse_v2 # AWS Graviton4
    env:
      TAR_NAME: libzvek-${{ matrix.target }}-${{ matrix.cpu }}.tar.gz 
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - run: |
          zig build -Dtarget=${{ matrix.target }} -Doptimize=ReleaseFast -Dcpu=${{ matrix.cpu }}
      - run: |
          tar -czf ${{ env.TAR_NAME }} -C zig-out/lib .
      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.TAR_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
