name: test

on:
  push

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - target: aarch64-macos
            runner: macos-latest
          - target: x86_64-linux
            runner: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
      - run: |
          zig build test -Dtarget=${{ matrix.target }}

